spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbquarkus
    username: postgres
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

server:
  port: 8090

logging:
  level:
    org:
      springframework=DEBUG: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: '*'
